version: '3'
volumes:
    rails101_pgdata:
      external: true
services: 
    db:
        image: postgres
        volumes: 
            - rails101_pgdata:/var/lib/postgresql/data
        environment: 
            POSTGRES_DB: rails101_development
            POSTGRES_USER: testadmin
            POSTGRES_PASSWORD: testuser123

    web:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes: 
            - .:/rails101
        ports:
            - "3000:3000"
        depends_on: 
            - db
         